spring:
  application:
    name: testConsumer-foo-config
  profiles:
    active: dev
    
---
spring:
  profiles: dev
write-value: develop-testConsumer-foo-dev-write-value

---
spring:
  profiles: product
write-value: develop-bm-testConsumer-dev-write-value-product

